---
title: "Climate Classification"
author: "Greg J. Schmidt"
date: "`r Sys.Date()`"
output: html_document
---
<html><head><style>li {list-style-type: none;}</style></head></html>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##A Climate Classification Outline Using Biologically Meaningful Indices for Modeling Plant Distribution

Abstract:

> Climate is an important factor in determining the broad patterns of species distribution and potential vegetation. But when similar or adjacent sites with similar soils are compared, it is not clear what if any difference in climate is responsible for differences in site potential. Ecological site descriptions commonly feature monthly and annual precipitation and temperature in climate descriptions and graphs. However, there is wide overlap among these parameters even where temperature and moisture are the primary drivers for the differences among vegetation types.
I propose several different parameters which have a better relationship to vegetation differences. Available moisture can only be determined when the timing of the inputs of precipitation and the outputs of potential evapotranspiration (PET) are considered with respect to growing season. Temperature can be understood both terms of optimal physiological activity, and lethal tissue limitations. The proposed parameters retain a connection to real world measurement units and are not obscure unitless indices derived from complex relationships. A Shiny application was developed to illustrate alternative graphs with which to compare different regions of the country. Maps were produced to illustrate the distribution of suggested classification intervals of the parameters.


> Seven climate indices were calculated to provide a base for an alternative climate classification and be physiologically informative for plant distribution modeling. The indices retain in real world units that can be directly related to climate change. The larger categories of the classification approximate major vegetation formations, but the indices can be subdivided into smaller, regular increments without the presumption that any given threshold implies precision in interpretation.

**Growing Season Temperature** is the positive average temperature of the warmest 6 months (any sub freezing months are counted as zeros). Körner (1998) demonstrated that the cold limit of forest growth across a wide range of latitude shared a growing season temperature of 6 to 7°C. It also follows that plant form and function is optimized according to temperatures likely to prevail during the growing season, irrespective of the length of the growing season. Six months is generally sufficient time to expect developmental maturity to reflect form and function within prevailing temperatures, whereas having a longer or shorter growing season is mostly a function of cumulative growth potential. Other systems use single month temperature thresholds (e.g. the Köppen-Geiger system, Kottek et al, 2006), annual biotemperature (Holdridge, 1947), or growing degree months base 5°C (Prentice et al, 1992) to represent the thermal zonation of vegetation. The 6 degree increments follow Holdridge (1947). Growing season temperature tends to play a dominant role in determining the altitudinal zonation of vegetation in mountains and latitudinal zonation at high latitudes, whereas winter temperatures tend to set the latitudinal zonation of middle and low latitudes.

**Annual Extreme Low/Coldest Mean Monthly Temperature**
**Coldest Mean Monthly Temperature** serves to characterize the seasonal variability in temperatures. Its divergence from growing season temperature is in indication of growing season length. For cold tolerant evergreen species, a cold month average above freezing means that photosynthesis can occur year round without damage related to desiccation due to frozen soil. The effects of the minimum monthly average are likely secondary to the importance of extreme minimum temperatures in the northern hemisphere, but are of primary importance in the southern hemisphere where low temperatures are not as extreme. The Köppen-Geiger system defines its latitudinal zones according to the coldest month, whereas the Holdridge system does not address seasonality.
**Annual Extreme Low** is coldest daily low temperature in a year corresponding to cold hardiness zones. According to Prentice et al, (1992) and Box (1996) hardiness of boreal species tends to be almost unlimited, whereas most temperate deciduous genera persist only down to -40°C. The diversity of temperate deciduous species drops sharply where annual extreme lows fall below -25°C. Subtropical broadleaf evergreens are frost tolerant to -15°C so long as the monthly averages are above freezing. The diversity of subtropical broadleaf evergreen and hardy palm species drops sharply below -10°C. Some tropical species lack any adaptation to cold and can sustain tissue damage at temperatures as high as 5°C, whereas others can withstand lows of -2°C. In Florida, the 0°C extreme minimum isotherm happens to correspond closely the 18°C minimum monthly average temperature set by the Köppen-Geiger system as the boundary between tropical and subtropical zones. In coastal regions in mid latitudes and at high altitudes at low latitudes, there are essentially frost free zones which support temperate and subtropical genera, mainly because average monthly temperatures do fall below 15°C.
Moisture index is the P/PET ratio of annual totals (correlating with dominant vegetation structure, i.e. desert to savanna to forest). This classification follows the break points used in Holdridge (1947) at a log base 2 increments. PET was calculated using a hybrid between the Hamon method (using temperature and daylength) and a term from the Hargreaves-Samoni method (daily temperature range as an indirect indicator of relative humidity and cloud cover) (Lu, McNulty, & Amatya, 2005). The final values were then calibrated to match the average PET calculated for a known mid-latitude humid climatic region (eastern United States) using the Holdridge biotemperature method (Lugo et al, 1999). [Other equations can easily be substituted if they are better supported.]

**Surplus/Deficit**
**Surplus** is the sum of each monthly precipitation exceeding the PET. A surplus exceeding 25 mm may be enough to overcome soil re-absorption in the upper 25 cm where half root mass is found and allow for seasonal growth of somewhat mesophytic vegetation in otherwise semiarid climates. In true deserts, this might happen only stochastically in different years, precluding perennial mesophytes.
Deficit is the sum of each monthly PET exceeding the precipitation. In most vegetation types, 95% of the root mass is located within 150 cm of the surface, to which depth is usually between 100 and 200 mm of available water holding capacity. A deficit of exceeding 150 mm would potentially use up all the available soil water, requiring plants in otherwise humid climates to go dormant.
Keys to Climate Zones
**Peak AET** is the maximum monthly AET. Peak AET correlates to the relative advantage in being deciduous in relation to seasonal drought, or the advantage of grasses over scrubs. The coincidence of high temperature with precipitation can also indicate the source of the precipitation being from thunderstorms and therefore a higher frequency of lightning ignitions. Only seasonally moist, seasonally dry, or subhumid climates are classified on the basis of peak AET. Months with mean temperatures exceeding 15°C have PET of at least 75 mm depending on sunlight and relative humidity. Therefore, rainy seasons in tropical climates, which are warm year-round, will usually have peak AET ≥ 75 mm. Plants in seasonally moist climates with peak AET < 75 mm are either more productive in cooler seasons or are dependent stored soil moisture.

##Keys to Climate Classification

###Macrothermoclimate

* 1a. Tc ≥ 0°C and Tclx ≥ -15°C
    * 2a. Tw ≥ 18°C
        * 3a. Tc ≥ 15°C and Tclx ≥ 0°C  ... Tropical
        * 3b. Tc < 15°C or Tclx < 0°C ... Subtropical
    * 2b. Tw < 18°C
        * 4a. Tw ≥ 6°C  ...  Oceanic
        * 4b. Tw < 6°C  ...  Andean
* 1b. Tc ≥ 0° C or Tclx < -15°C
    * 5a. Tw ≥ 12°C  ...  Temperate
    * 5b. Tw < 12°C
        * 6a. Tw ≥ 6°C  ...  Boreal
        * 6b. Tw < 6°C  ...  Arctic

###Macrombroclimate


* 1a. P/PET ratio ≥ 1 and total monthly deficit < 150 mm   ...   Isopluvial
* 1b. P/PET ratio < 1 or total monthly deficit ≥ 150 mm
    * 2a. P/PET ratio > 0.5 or total monthly surplus ≥ 25 mm or peak AET ≥ 75 mm
        * 3a. peak AET ≥ 75 mm (monsoonal with rainfall occurring with warm weather)   ...   Pluviothermic
        * 3b. peak AET < 75 mm (Mediterranean with drought occurring with warm weather and precipitation occurring with cool weather)   ...   Xerothermic
    * 2b. P/PET ratio < 0.5 and total monthly surplus < 25 mm and peak AET < 75 mm   ...   Isoxeric

###Temperature Regime
* 1a. Tc ≥ 0°C and Tclx ≥ -15°C
    * 2a. Tw ≥ 18°C
        * 3a. Tc ≥ 15°C and Tclx ≥ 0°C ... Tropical
            * Tw ≥ 24°C
                * Tc ≥ 20°C and Tclx ≥ 5°C ... Hot Mesotropical
                * Tc < 20°C or Tclx < 5°C ... Hot Cryotropical
            * Tw < 24°C ... Premontane Tropical
        * 3b. Tc < 15°C or Tclx < 0°C ... Subtropical
            * Tc ≥ 10°C and Tclx ≥ -5°C
                * Tw ≥ 24°C ... Hot Thermosubtropical
                * Tw < 24°C ... Warm Thermosubtropical
            * Tc < 10°C or Tclx < -10°C
                * Tc ≥ 5°C and Tclx ≥ -10°C
                    * Tw ≥ 24°C ... Hot Mesosubtropical
                    * Tw < 24°C ... Warm Mesosubtropical
                * Tc < 5°C or Tclx < -10°C
                    * Tw ≥ 24°C ... Hot Cryosubtropical
                    * Tw < 24°C ... Warm Cryosubtropical
    * 2b. Tw < 18°C
        * 4a. Tw ≥ 6°C ... Oceanic
            * Tw ≥ 12°C
                * Tc ≥ 5°C and Tclx ≥ -10°C ... Montane Subtropical
                * Tc < 5°C or Tclx < -10°C ... Mild Oceanic
            * Tw < 12°C
                * Tc ≥ 5°C and Tclx ≥ -5°C ... Subandean
                * Tc < 5°C or Tclx < -10°C ... Cool Oceanic
        * 4b. Tw < 6°C ... Andean
* 1b. Tc ≥ 0° C or Tclx < -15°C
    * 5a. Tw ≥ 12°C ...... Temperate
        * Tc ≥ -10°C or Tclx ≥ -25°C
            * Tw ≥ 18°C
                * Tc ≥ -5°C or Tclx ≥ -20°C ... Warm Thermotemperate
                * Tc < -5°C or Tclx < -20°C ... Warm Mesotemperate
            * Tw < 18°C
                * Tw ≥ 15°C ... Mild Temperate
                * Tw < 15°C ... Presubalpine
        * Tc < -10°C or Tclx < -25°C
            * Tc ≥ -25°C or Tclx ≥ -40°C
                * Tw ≥ 15°C
                    * Tw ≥ 18°C ... Warm Cryotemperate
                    * Tw < 18°C ... Mild Cryotemperate
                * Tw < 15°C ... Hemiboreal
            * Tc < -10°C or Tclx < -25°C ... Warm Boreal
      * 5b. Tw < 12°C
        * 6a. Tw ≥ 6°C ... Boreal
            * Tc ≥ -10°C and Tclx ≥ -25°C ... Subalpine
            * Tc < -10°C or Tclx < -25°C ... Cool Boreal
        * 6b. Tw < 6°C ... Arctic
            * Tc ≥ -10°C and Tclx ≥ -25°C ... Alpine
            * Tc < -10°C or Tclx < -25°C ... Arctic
            
###Moisture Zones

* 1a. P/PET ratio ≥ 2 ... Perhumid
* 1b. P/PET ratio < 2
    * 2a. P/PET ratio ≥ 1.414 ... Moist Humid
    * 2b. P/PET ratio < 1.414
        * 3a. P/PET ratio ≥ 1 ... Dry Humid
        * 3b. P/PET ratio < 1
            * 4a. P/PET ratio ≥ 0.707 ... Moist Subhumid
            * 4b. P/PET ratio < 0.707
                * 5a. P/PET ratio ≥ 0.5 ... Dry Subhumid
                * 5b. P/PET ratio < 0.5
                    * 6a. P/PET ratio ≥ 0.25 ... Semiarid
                    * 6b. P/PET ratio < 0.25
                        * 7a. P/PET ratio ≥ 0.125 ... Arid
                        * 7b. P/PET ratio < 0.125 ... Perarid

###Formulae
Monthly potential evapotranspiration: $$PET = 0.008404 * 216.7*\frac{exp(17.26939*\frac{T}{T+237.3})}{T+273.3}*Ra*dM*(Tmax-Tmin)^{0.5}$$

where

Declination: $dec = 0.409*sin(2*\pi*Md/365 – 1.39)$

Sunset Angle: $hs = acos(-tan(Latitude/360*2*\pi) * tan(declination)) [-1\to 1]$

Potential Solar Radiation: $Ra = 117.5 * (hs*sin(Latitude/360*2*\pi)*sin(dec) + cos(Latitude/360*2*\pi)*cos(dec)*sin(hs)) /\pi$

T = mean monthly temperature

Tmax = mean monthly daily high temperature

Tmin = mean monthly daily low temperature

Md = mid-month day of year

dM = total days in month

Simple approximation of monthly PET: $$PET = 5 * BT$$

where

BT = positive mean monthly temperature $[0\to\infty]$ (values below zero set to zero) or “biotemperature”.

Mean annual extreme low temperature (approximated): $Tclx = -9.921 + 1.248*Tcl + -0.03829*L + 0.000904*A + -0.0000219 * L*A$

where

Tcl = low temperature of coldest month

L = latitude

A = altitude above sealevel
Other variables

Tc = mean temperature of the coldest month

Tw = mean positive (subzero temperatures counted as zero) temperature of the warmest 6 months

P = precipitation

AET = lesser value among monthly P and PET, approximating “actual evapotranspiration” without considering affects of soil moisture storage or runoff.

Deficit = .total monthly deficit is calculated by summing for the entire year each monthly amount of PET in excess of P (subtract P from PET if P is less than PET; zero if P ≥ PET).

Surplus = total monthly surplus is calculated by summing for the entire year each monthly amount of P in excess of PET (subtract PET from P if PET is less than P; zero if P <= PET).
 
###References

####Hardiness Zone Map of the World recreated from these sources: 

Daly, C., Halbleib, M., Smith, J.I., Gibson, W.P., Doggett, M.K., Taylor, G.H., Curtis, J., and Pasteris, P.A. 2008. Physiographically-sensitive mapping of temperature and precipitation across the conterminous United States. International Journal of Climatology, 28: 2031-2064. (http://prism.oregonstate.edu/normals/) 

Daly, C., Widrlechner, M.P., Halbleib, M.D., Smith, J.I. and Gibson, W.P., 2012. Development of a new USDA plant hardiness zone map for the United States. Journal of Applied Meteorology and Climatology, 51(2), pp.242-264. 

Hijmans, R.J., S.E. Cameron, J.L. Parra, P.G. Jones and A. Jarvis, 2005. Very high resolution interpolated climate surfaces for global land areas. International Journal of Climatology 25: 1965-1978. (http://www.worldclim.org/version1) 

Magarey, R.D., Borchert, D.M. and Schlegel, J.W., 2008. Global plant hardiness zones for phytosanitary risk analysis. Scientia Agricola, 65(SPE), pp.54-59. 


####Alternative Climate Classifications: 

Holdridge, L.R., 1947. Determination of world plant formations from simple climatic data. Science, 105(2727), pp.367-368. 

Lugo, A.E., Brown, S.L., Dodson, R., Smith, T.S. and Shugart, H.H., 1999. The Holdridge life zones of the conterminous United States in relation to ecosystem mapping. Journal of biogeography, 26(5), pp.1025-1038. 

Kottek, M., Grieser, J., Beck, C., Rudolf, B. and Rubel, F., 2006. World map of the Köppen-Geiger climate classification updated. Meteorologische Zeitschrift, 15(3), pp.259-263. 

Rivas-Martínez, S., 2004. Global bioclimatics. Classificación Bioclimática de la Tierra. http://www.globalbioclimatics.org/form/maps.htm 

Thornthwaite, C.W., 1948. An approach toward a rational classification of climate. Geographical review, 38(1), pp.55-94. 

Alternative PET calculations: 

Lu, J., Sun, G., McNulty, S.G. and Amatya, D.M., 2005. A comparison of six potential evapotranspiration methods for regional use in the southeastern United States 1. JAWRA Journal of the American Water Resources Association, 41(3), pp.621-633. 

####Other publications relating climate to vegetation: 

Faber-Langendoen, D., Keeler-Wolf, T., Meidinger, D., Josse, C., Weakley, A., Tart, D., Navarro, G., Hoagland, B., Ponomarenko, S., Saucier, J.P. and Fults, G., 2012. Classification and description of world formation types. Part II (Description of formation types). Faber-Langendoen, D.; Keeler-Wolf, T.; Meidinger, D.; Josse, C.; Weakley, A.; Tart, D.; Navarro, G.; Hoagland, B.; Ponomarenko, S.; Saucier, JP; Fults, G.; Helmer, E. 2012. Classification and description of world formation types. Part II (Description of formation types). Hierarchy Revisions Working Group, Federal Geographic Data Committee, FGDC Secretariat, US Geological Survey and NatureServe, Reston, VA and Arlington, VA. 

Box, E.O., 1996. Plant functional types and climate at the global scale. Journal of Vegetation Science, 7(3), pp.309-320. 

Körner, C., 1998. A re-assessment of high elevation treeline positions and their explanation. Oecologia, 115(4), pp.445-459.

Prentice, I.C., Cramer, W., Harrison, S.P., Leemans, R., Monserud, R.A. and Solomon, A.M., 1992. Special paper: a global biome model based on plant physiology and dominance, soil properties and climate. Journal of biogeography, pp.117-134. 

Sakai, A., 1981. Freezing resistance of broad-leaved evergreen trees in the warm-temperate zone. Low temperature Science. Ser. B, Biological sciences, 38, pp.1-14. 

Schenk, H.J. and Jackson, R.B., 2002. The global biogeography of roots. Ecological monographs, 72(3), pp.311-328. 

Wright, I.J., Dong, N., Maire, V., Prentice, I.C., Westoby, M., Díaz, S., Gallagher, R.V., Jacobs, B.F., Kooyman, R., Law, E.A. and Leishman, M.R., 2017. Global climatic drivers of leaf size. Science, 357(6354), pp.917-921.
